//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : Auxiliar.cs
//  @ Date : 26/09/2021
//  @ Author : 
//
//


public class Auxiliar : Persona{
	public object Id ;
}
