//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : Consulta.cs
//  @ Date : 26/09/2021
//  @ Author : 
//
//

namespace ClinicaVeterinaria.App.Dominio
{
    public class Consulta
    {
        public string Anotacion { get; set; }
        public string ListaMedicamentos { get; set; }
        public Veterinario Veterinario { get; set; }
        public Auxiliar Auxiliar { get; set; }
        public string Fecha { get; set; }
    }
}
