//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : Consulta.cs
//  @ Date : 26/09/2021
//  @ Author : 
//
//


public class Consulta {
	public object Anotacion ;
	public object Lista Medicamentos ;
	public object Veterinario ;
	public object Auxiliar ;
	public object Fecha ;
}
