//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : Historia clinica.cs
//  @ Date : 26/09/2021
//  @ Author : 
//
//

namespace ClinicaVeterinaria.App.Dominio
{
    public class HistoriaClinica
    {
        public int Id { get; set; }
        public string Historia { get; set; }
    }
}