//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : Mascota.cs
//  @ Date : 26/09/2021
//  @ Author : 
//
//

namespace ClinicaVeterinaria.App.Dominio
{
    public class Mascota
    {
        public Dueño Dueño { get; set; }
        public string FechaNacimiento { get; set; }
        public string Nombre { get; set; }
        public string Tipo { get; set; }
    }
}
