//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : Persona.cs
//  @ Date : 26/09/2021
//  @ Author : 
//
//

namespace ClinicaVeterinaria.App.Dominio{
public class Persona {
    public int Id { get; set; }
    public int Cedula { get; set; }
    public string Nombre{ get;set;}
    public string Apellido{ get;set;}
	public string Celular{ get;set;}
	public string Direccion { get;set;}
	public string Ciudad { get;set;}
}
}