//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : Persona.cs
//  @ Date : 26/09/2021
//  @ Author : 
//
//


public class Persona {
	public object Id ;
	public object Nombre ;
	public object Apellido ;
	public object Celular ;
	public object Direccion ;
	public object Ciudad ;
}
