//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : Tipo de animal.cs
//  @ Date : 26/09/2021
//  @ Author : 
//
//


public class Tipo de animal {
	public object Perro ;
	public object Gato ;
}
