//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : Veterinario.cs
//  @ Date : 26/09/2021
//  @ Author : 
//
//


public class Veterinario : Persona{
	public object Id ;
	public object Horario Dia ;
}
