//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : Veterinario.cs
//  @ Date : 26/09/2021
//  @ Author : 
//
//

namespace ClinicaVeterinaria.App.Dominio{
public class Veterinario : Persona{
}
}